# blender_tool.py
# Saves a Blender Python (bpy) script and opens it in Blender.
#
# How it works:
#   1. cad_agent generates a bpy script (LLM writes it)
#   2. We save it to jarvis/blender_scripts/
#   3. We launch Blender with that script via command line
#   4. Blender opens with the model already built — ready to edit or export STL

import subprocess
import pathlib

# Path to Blender executable on this Mac
BLENDER_PATH = "/Users/alexsalamati/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/MacOS/Blender"

# Where to save generated scripts
SCRIPTS_DIR = pathlib.Path.home() / "Personal Project" / "Desktop assistant" / "jarvis" / "blender_scripts"


def run_script(script_code: str, model_name: str) -> str:
    """
    Save a bpy script and open it in Blender.

    Args:
        script_code: Full Python/bpy script generated by the LLM.
        model_name:  Used as the filename.

    Returns:
        A status string.
    """
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)

    safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in model_name)
    script_path = SCRIPTS_DIR / f"{safe_name}.py"

    script_path.write_text(script_code, encoding="utf-8")
    print(f"[blender_tool] Saved script to {script_path}")

    # Check Blender exists
    if not pathlib.Path(BLENDER_PATH).exists():
        return f"Blender not found at {BLENDER_PATH}. Check the path in tools/blender_tool.py."

    # Open Blender and run the script — Blender stays open so you can edit
    print(f"[blender_tool] Opening Blender with script...")
    subprocess.Popen([BLENDER_PATH, "--python", str(script_path)])

    return f"Blender opened with '{model_name}'. Script saved to {script_path}"
